class ApplicationConstants:
    def __init__(self):
        pass

    # Properties constants
    KEYSTONE_AUTH_URL_KEY_PROPERTY = "KEYSTONE_AUTH_URL"
    KEYSTONE_AUTH_ENDPOINT_KEY_PROPERTY = "KEYSTONE_AUTH_ENDPOINT"
    KEYSTONE_PROJECT_ID_KEY_PROPERTY = "KEYSTONE_PROJECT_ID"
    KEYSTONE_USER_ID_KEY_PROPERTY = "KEYSTONE_USER_ID"
    KEYSTONE_PASSWORD_KEY_PROPERTY = "KEYSTONE_PASSWORD"

    # Swift constants
    SWIFT_URL_PROPERTY = "SWIFT_URL"
    SWIFT_URL_STORAGE_ENDPOINT_PROPERTY = "SWIFT_URL_STORAGE_ENDPOINT"
    SWIFT_INPUT_FILES_PREFIX_KEY_PROPERTY = "SWIFT_INPUT_FILES_PREFIX"
    SWIFT_OUTPUT_FILES_PREFIX_KEY_PROPERTY = "SWIFT_OUTPUT_FILES_PREFIX"
    SWIFT_CONTAINER_NAME_KEY_PROPERTY = "SWIFT_CONTAINER_NAME"
    SWIFT_TEMP_URL_KEY_PROPERTY = "SWIFT_TEMP_URL_KEY"
    TEMP_URL_EXPIRATION_TIME = 10800

    # Header constants
    CONTENT_TYPE = "Content-Type"

    # OCCI constants
    JSON_CONTENT_TYPE = "application/json"

    # Configuration constants
    DEFAULT_CONFIG_FILE_PATH = "resources/config.ini"
